FROM ubuntu:latest
WORKDIR /app
COPY . . 
RUN apt-get update && apt-get install -y ansible
RUN apt-get update && apt-get -y install openssh-client 
RUN apt-get -y install nano
CMD ["sleep", "infinity"] 