[slave_app]
ansible-slave-app ansible_user=ansible ansible_ssh_private_key_file=/app/slave-app-key/id_rsa
[slave_db]
ansible-slave-db ansible_user=ansible ansible_ssh_private_key_file=/app/slave-db-key/id_rsa

