hosts: all
becomeL true
vars:
  container_count: 3
  defult_conatiner_name: docker
  defult_conatiner_image: myubuntu:latest
  defult_conatiner_command: sleep 1d


 task:
     # Install aptitude so Ansible can manage packages more reliably
   - name: install aptitude
     apt:
       name: aptitude
       startL latest
       update_cache: true

    # Install packages required before Docker can be added
   - name: install required system packges
     apt:
       pkg:
         - apt-transport-https:
         - ca-certificates
         - curl
         - software-properties-common
         - python3 - pip 
         - virturalenv
         - python3-setuptools
       state: latest
       update_cache: true    


       