services:
  ansible-master:
    image: ansible-master:v0.1 
    container_name: ansible-master


  ansible-slave-app:
    image: ansible-slave:v0.1
    container_name: ansible-slave-app
    ports:
     - "2222:22"
    volumes:
     - myssh:/home/ansible/.ssh
     - /var/run/docker.sock:/var/run/docker.sock
     
 

  ansible-slave-db:
    image: ansible-slave:v0.1
    container_name: ansible-slave-db
    ports:
     - "2223:22"
    volumes:
     - myssh:/home/ansible/.ssh
     - /var/run/docker.sock:/var/run/docker.sock

volumes:
 myssh: 
 




  